id: I644AC850
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-09 14:54:55.291735
last_modified: 2023-02-09 14:54:55.291876
source_metadata:
  title: 'RK: Bodhisatvapiṭaka'
  language: bo
bases:
  91B9:
    base_file: 91B9.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
